// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkLXiFe4LmyQeGWWlZHYDxlzMnlZZcGwQ',
    appId: '1:1068664984586:web:101a9c3877a8d0bf847bf3',
    messagingSenderId: '1068664984586',
    projectId: 'openbook-4155f',
    authDomain: 'openbook-4155f.firebaseapp.com',
    storageBucket: 'openbook-4155f.appspot.com',
    measurementId: 'G-8BEPCDKFHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsgTiNXgaXucTjq1i9H-WVQUOwwAMvvKo',
    appId: '1:1068664984586:android:a39cb90bb3f7d8b1847bf3',
    messagingSenderId: '1068664984586',
    projectId: 'openbook-4155f',
    storageBucket: 'openbook-4155f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApnMgvqbKPbm1B2QbYUikau0ARZyKMuQY',
    appId: '1:1068664984586:ios:f3e6d062407be3dc847bf3',
    messagingSenderId: '1068664984586',
    projectId: 'openbook-4155f',
    storageBucket: 'openbook-4155f.appspot.com',
    androidClientId: '1068664984586-p3dkiinhfd1jnvlncagu27gvjrcu0dia.apps.googleusercontent.com',
    iosClientId: '1068664984586-9h32qk292r2oi4chrcu8olj7g2m353cl.apps.googleusercontent.com',
    iosBundleId: 'com.example.openBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApnMgvqbKPbm1B2QbYUikau0ARZyKMuQY',
    appId: '1:1068664984586:ios:f3e6d062407be3dc847bf3',
    messagingSenderId: '1068664984586',
    projectId: 'openbook-4155f',
    storageBucket: 'openbook-4155f.appspot.com',
    androidClientId: '1068664984586-p3dkiinhfd1jnvlncagu27gvjrcu0dia.apps.googleusercontent.com',
    iosClientId: '1068664984586-9h32qk292r2oi4chrcu8olj7g2m353cl.apps.googleusercontent.com',
    iosBundleId: 'com.example.openBook',
  );
}
